### Primera solicitud registro nuevo
POST http://localhost:3001/Clientes/Registrar HTTP/1.1
Content-Type: application/json

{
    "nombre":"becerro",
    "cedulaRif":2160,
    "direccion":"palo woco",
    "tlf":"04126667000",
    "tipo":"G",
    "ultimoNumero":2,
    "token":"sdsad"
}

### Segunda solicitud actualizar todo
PUT http://localhost:3001/Clientes/Actualizar HTTP/1.1
Content-Type: application/json

{
    "id":2,
    "nombre":"becerro2",
    "cedulaRif":5670,
    "direccion":"kako",
    "tlf":"04120000000",
    "tipo":"h",
    "ultimoNumero":1,
    "token":"sdsad"
}
###solicitar datos
GET http://localhost:3001/Clientes/Datos HTTP/1.1

### solicitud para activar o desactivar

PATCH  http://localhost:3001/Clientes/Estado HTTP/1.1
Content-Type: application/json

{
    "id":2,
    "estado":true,
    "token":"sdsad"
}
###
PATCH  http://localhost:3001/Clientes/Estado HTTP/1.1
Content-Type: application/json

{
    "id":2,
    "estado":false,
    "token":"sdsad"
}


###
DELETE http://localhost:3001/Clientes/Eliminar/7 HTTP/1.1
Authorization: Bearer tu_token_secreto


